### ISSUE TITLE
Non-interactive group invites

### ISSUE THREAD

**Issue by burdges** [mlswg/mls-architecture#102]
I believe messangers like matrix and wire need to post messages into rooms when sending invites, which possibly creates spam if room invites should be automated somehow.  It'd make sense to have purely cryptographic invites which trigger no room action unless the user acts upon the invite.

We cannot give actual decryption keys this way because they'd often change before the user could act upon the invite.  It's likely this places off-room invites outside the scope of the core protocol, but maybe they fit somewhere.

**Comment by kkohbrok** [comment]
If the user has to be able to join the group (assuming a room corresponds to a group) while none of the group members is online, then an external commit is really the only option. If there is support for an external commit, i.e. if group members upload a GroupInfo somewhere with every commit, then an invite could contain a token that the invitee could use to authenticate to the server to obtain the GroupInfo and perform the external commit. In addition, the token could also be used as a PSK for the external commit.

If it's ok that the link only works if another member is online, then such a token could be used to have the server send an Add proposal to the group, again optionally, the token can also be used as a PSK in this case.

Does that sound reasonable? It sounds like the use case might be relevant enough to warrant a section in the architecture doc.

**Comment by burdges** [comment]
An external commit means the party adding the new user must notify the room before the new user chooses to join?  There exist use cases where this looks undesirable, but maybe it's desirable in other cases, not really sure.

Yes PSKs add something here nice, presumably it's derived some some recent group state.

**Comment by kkohbrok** [comment]
As you mentioned, other members that make commits would also have to upload GroupInfos for the respective epochs to keep the key material up to date. If that happens programmatically anyway (which is up to the application and the rest of the infrastructure), then there is no need for any extra notification. Again, it depends a bit on the specific setup, but I don't think there's an inherent need to notify other group members of the invite.

**Comment by rohan-wire** [comment]
> An external commit means the party adding the new user must notify the room before the new user chooses to join? There exist use cases where this looks undesirable, but maybe it's desirable in other cases, not really sure.

The authorization policy of the group is defined outside the MLS protocol, but what is clear is that if an invalid Commit arrives, the members should ignore it. Likewise an invalid Proposal would not get incorporated into any Commits.
So, if the use case of an External Commit (or External Proposal) is undesirable, I believe the spec allows you to create a policy that makes it invalid.

**Comment by rohan-wire** [comment]
I chatted with @burdges. He agreed that using External Proposals or an out-of-band protocol were both reasonable approaches to the problem that motivated him to write this issue. He said we can Close the issue.
