### ISSUE TITLE
Missing(correct) Link/Reference for CHK19

### ISSUE THREAD

**Issue by rohan-wire** [mlswg/mls-architecture#115]
The Reference for [CHK19] has the wrong link (the link for [BCK21]). Can someone please provide the correct link?

**Comment by beurdouche** [comment]
@kkohbrok @br-hale Can you confirm this is supposed to be for "Efficient Post-Compromise Security Beyond One Group" and provide a link please?

**Comment by br-hale** [comment]
The title can be corrected to "The Complexities of Healing in Secure Group Messaging: Why Cross-Group Effects Matter" with link https://www.usenix.org/system/files/sec21-cremers.pdf

**Comment by beurdouche** [comment]
Thank you @br-hale, I’ll handle the change.

**Comment by beurdouche** [comment]
Fixed by 9a14e907d909b424b8097966d28d7e075b4decc1
