### ISSUE TITLE
possibly detect?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#127]
_Comment by @paulwouters_

~~~ 
   The
   protocol is designed such that this only results in a group no longer
   being functional and the group members possibly detecting this and
   requesting reinitialization.
~~~
It scares me a bit that this could possibly not be detected at all? What is the scenario where it cannot be detected?

**Comment by bifurcation** [comment]
It's actually non-trivial to guarantee detection.  Consider a scenario like the following:

* A, B, C, D are in a group
* The DS decides to partition the group into (AB) (CD)
* The DS forwards commits and messages within a partition, but not across partitions.
* As a result, the two subgroups work fine, but they diverge from each other

This will be immediately obvious if two participants in opposite partitions ever try to compare state across the partition boundary, say by checking whether a message arrived or even by comparing the `epoch_authenticator` value.  But it will be invisible if nobody does -- it just looks like the other partition is offline at the moment.  And note that comparing across the partition boundary has to be done out of band, because the DS is blocking in-band comms across the boundary.

To prevent this with any reliability, you would need a consensus protocol by which a quorum of members verify that they've received a Commit.  And even then, the members outside any particular quorum could be partitioned.  In any case, designing a consensus protocol is clearly outside the MLS WG charter.

The silver lining here, as the document notes, is that the protocol fails closed.  If two members have different views of the group, then they cannot communicate.

**Comment by Bren2010** [comment]
This is only true wrt to handshake messages. The DS can still reorder and provide an inconsistent view of application messages. We intentionally punted this to an extension (which I realize now we never specified in the extensions doc) to give applications leeway in the ordering/delivery guarantees provided to application messages. Handshake messages require reliable and in-order but application messages may or may not.
