### ISSUE TITLE
Signed confirmations?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#128]
_Comment by @paulwouters_

~~~ 
   Other forms of Delivery Service misbehavior are still possible that
   are not easy to detect.  For instance, a Delivery Service can simply
   refuse to relay messages to and from a given client.  Without some
   sort of side information, other clients cannot generally detect this
   form of Denial of Service (DoS) attack.
~~~
Would it not be possible for clients to report a signed receive receipt? While that might take forever for an offline client, it would allow tracking that a specific user hasn't confirmed receiveing messages for a long time? (receive receipt being different from a read receipt. I guess it is a privacy leak to know a user's device got the message...)

**Comment by bifurcation** [comment]
This was discussed by the WG, and actually included in the protocol draft for a while.  But there was consensus more recently to move it to an [extensions document](https://www.ietf.org/archive/id/draft-robert-mls-extensions-00.html#name-appack).

**Comment by rohan-wire** [comment]
This is definitely a place where there could be multiple solutions depending on the application's requirements.
The currently AppAck proposal in the extensions document is pretty heavy weight (each Commit has to acknowledge all the messages received), and could result in an explosion of messages. There could easily be other solutions which are lighter touch, but piggyback on existing traffic so members can detect messages not being delivered.

**Comment by paulwouters** [comment]
okay. feel free to close this item
