### ISSUE TITLE
encrypted meaning object, not transport?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#129]
_Comment by @paulwouters_

~~~ 
      Additional authenticated data, sent unencrypted in an otherwise
      encrypted message.
~~~
I assume this means object encryption, and that the unencrypted part of the message would still be encrypted with a TLS transport? Can that be written more explicitely ?

**Comment by bifurcation** [comment]
Yes, that's how I understand it.  The AAD is not covered by the MLS encryption, but might be covered by encryption provided by the DS.

**Comment by rohan-wire** [comment]
> _Comment by @paulwouters_
> I assume this means object encryption, and that the unencrypted part of the message would still be encrypted with a TLS transport? Can that be written more explicitely ?

I think [Assumptions on Transport Security Links](https://www.ietf.org/archive/id/draft-ietf-mls-architecture-09.html#name-assumptions-on-transport-se) would be a logical place for to explain the benefits of transporting MLS messages in a TLS-protected channel.
