### ISSUE TITLE
Deniability

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#130]
_Comment by @paulwouters_

I assume that some thought has gone into this, and a decision was made not to provide this as a core feature, likely due to the limited usefulness in eg a court system, when logged messages (deniable or not) are recovered? I assume it was not easy to add this property and it was therefor mostly left out? Because of course it would be nicer to have it than to not have it.

**Comment by burdges** [comment]
Arguably deniability does more harm than good: https://mailarchive.ietf.org/arch/msg/mls/Kk6qai3kEza8B-L-_5R-qsEjtK0/

I've not followed recent developments but I think MLS left the door open to deniability without actually specifying deniability.

**Comment by bifurcation** [comment]
That's exactly the balance we're trying to strike.  Deniability is not a core feature, but it would be nice if some folks could figure out how to operate MLS in a deniable mode.  See also https://github.com/mlswg/mls-protocol/issues/816

**Comment by paulwouters** [comment]
that's what i thought, but mostly curious about that discussion. thanks for the link !
