### ISSUE TITLE
Section 1

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#131]
_Comment by @paulwouters_

~~~ 
   Clients may wish to do the following:
~~~
It is not really a client who wants this but a user (who can be using multiple clients). I also find "member" confusing, because I keep thinking of a user and not a client. Perhaps using "member client" would clarify this?

**Comment by bifurcation** [comment]
Personification of software aside, I think this phrasing is fine if you view the client as the user's agent.

"Member" is used so ubiquitously that "member client" would be onerous.

**Comment by rohan-wire** [comment]
I will add that in the IoT use cases, it really _is_ the _client_ that is deciding it wants to do those things. If you want a concrete example, imagine you are doing logging of sensitive data across different nodes in a handful of kubernetes nodes. The logging clients = MLS clients add and remove clients as they become relevant.
