### ISSUE TITLE
Section 2, use of client and member

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#133]
_Comment by @paulwouters_

The use of client, member and someone/everyone is a little inconsistent, eg see:

~~~ 
        For instance, any member can add or remove another client in a group.
~~~
I assume a member is identical to a client, but is a member of the group. But then the above "clients may wish to do the following:" should not be used with "remove one or more members from an existing group;"

Perhaps just adding a line saying "a member is a client that is within a group" might be useful? Or say that client and member are used interchangably, but that a client could be no member of any group ?

I guess this is further explained in [Section 2.1](https://www.ietf.org/archive/id/draft-ietf-mls-architecture-09.html#section-2.1) afterwards. It might be better to bring this up a little earlier?

**Comment by rohan-wire** [comment]
Yes, I think bringing forward "a member is a client that is within a group" would be useful.

A member can remove another member, and can add a client (not yet a member)
A (non-member) client can remove a member (via an external remove proposal), and can add itself (via an external commit or external add proposal).
