### ISSUE TITLE
offline clients

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#144]
_Comment by @paulwouters_

~~~ 
      any client which
      is persistently offline may still be holding old keying material
~~~
Should there be client recommendations to delete old keying material even if offline for some long amount of time? Can the document recommend some? Is 4 weeks reasonable ? The risk seems to be like "old phones" kept in a drawer, likely depleted of power, but still likely to be powered up without disassembly of flash storage, where it could still wipe the content based on a (large) timer. I feel not giving ANY guidance is a hole in the specification.

**Comment by bifurcation** [comment]
I don't think guidance here would be tremendously useful.  It's a pretty rare case, and vendors that care can solve it pretty straightforwardly.

**Comment by rohan-wire** [comment]
I think it is up to the _applications_ to define what "old" means (could be anything from 15 minutes to 1 year AFAIK), but I think the architecture document should provide guidance to delete it if it is.

**Comment by paulwouters** [comment]
fair enough. feel free to close
