### ISSUE TITLE
Section 7.4.2

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#148]
_Comment by @paulwouters_

~~~ 
This threat can be mitigated by having initial keys expire.
~~~
Again I wish there would at least be some advise on the expiry period, even if it is a ballpark. Are we talking 1h? 1d? 1m? If it depends on things, what things? (perhaps this is explained in the protocol draft) Maybe a _RECOMMENDATION:_ ?

**Comment by rohan-wire** [comment]
These timers are very application specific.

**Comment by paulwouters** [comment]
that's fair (yet frustrating for implementers reading this who need to put something in the code)
