### ISSUE TITLE
Deletion schedule

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#155]
_Comment by @paulwouters_

~~~ 
   Messages sent
   during the client's membership are also secure as long as the client
   has properly implemented the MLS deletion schedule.
~~~
Is this the equivalent of proprietary IM clients "auto delete" or "view once" type messaging? "MLS deletation schedule" has not been defined before it is mentioned here. What is this?

**Comment by bifurcation** [comment]
It is not the equivalent of "expiring messages" features.  It's a forward security provision.

**Comment by rohan-wire** [comment]
The [Deletion Schedule](https://www.ietf.org/archive/id/draft-ietf-mls-protocol-16.html#name-deletion-schedule) is defined in the protocol document. Perhaps a pointer would be useful.
