### ISSUE TITLE
Denying external proposals

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#156]
_Comment by @paulwouters_

~~~ 
   External signers can submit proposals for changes to the group,
   and new joiners can use an external join to add themselves to the
   group.
~~~
Is there a method for always denying these? This seems like a DoS vector where a group is spammed with change proposals or join requests?

**Comment by bifurcation** [comment]
External signers have to be explicitly allowed, either by publishing a GroupInfo (each of which allows a single external joiner) or by registering the signer in the [`external_signers` group extension](https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.html#section-12.1.8.1).  Either way, I don't think DoS is an issue.

**Comment by rohan-wire** [comment]
You can also authorize external joiners/proposers at the application layer.

**Comment by paulwouters** [comment]
thanks for the update. feel free to close
