### ISSUE TITLE
Review from Valery Smyslov (ART)

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-architecture#175]
```
Reviewer: Valery Smyslov
Review result: Ready with Issues

I am the assigned ART directorate reviewer for this document. These comments
were written primarily for the benefit of the ART area directors.  Document
editors and WG chairs should treat these comments just like any other last call
comments.

I reviewed the -09 version of the draft before. Some of my concerns were
addressed in the -10 version. I still have the following issues with the
document.

1) It is not clear from the document if it is ever possible for clients
that support only version x of the protocol to join the group that was formed
using version y of the protocol, but in fact all the current members of this
group support both versions. It seems to me that this scenario is common in
situations when newer version of the protocol becomes available: during some
period of time some clients will support both new and old version, while the
rest will support only old version. If some upgraded clients form a group, they
will probably choose the newest version of the protocol, so the un-upgraded
clients won't be able to join it. I think that this scenario should be
addressed in the document.

2) It is still not clear for me whether the type of DS (Strongly Consistent vs
Eventually Consistent) affects clients that use this DS. In other words - does
clients' behaviour depend on the type of DS or not, and if yes, then how it is
handled in the protocol.

3) The issue of inability for a client to remove itself from the group by
itself seems unsolvable. I would like to see recommendations in the document
for clients wishing to exclude themselves in situations when other members for
some reasons don't cooperate in this process.

While I think these issues are important, I'd leave them on ADs' discretion.
```

**Comment by dconnolly** [comment]
> 1) It is not clear from the document if it is ever possible for clients
that support only version x of the protocol to join the group that was formed
using version y of the protocol, but in fact all the current members of this
group support both versions. It seems to me that this scenario is common in
situations when newer version of the protocol becomes available: during some
period of time some clients will support both new and old version, while the
rest will support only old version. If some upgraded clients form a group, they
will probably choose the newest version of the protocol, so the un-upgraded
clients won't be able to join it. I think that this scenario should be
addressed in the document.

Is this not addressed sufficiently in https://github.com/mlswg/mls-architecture/blob/main/draft-ietf-mls-architecture.md#compatibility-with-future-versions-of-mls ?

<img width="838" alt="image" src="https://user-images.githubusercontent.com/552961/210176367-d74f1861-2ac8-4fb7-beda-f8764ee24be6.png">

**Comment by rohan-wire** [comment]
> > 1. It is not clear from the document if it is ever possible for clients
> >    that support only version x of the protocol to join the group that was formed
> >    using version y of the protocol, but in fact all the current members of this
> >    group support both versions. It seems to me that this scenario is common in
> >    situations when newer version of the protocol becomes available: during some
> >    period of time some clients will support both new and old version, while the
> >    rest will support only old version. If some upgraded clients form a group, they
> >    will probably choose the newest version of the protocol, so the un-upgraded
> >    clients won't be able to join it. I think that this scenario should be
> >    addressed in the document.
> 
> Is this not addressed sufficiently in https://github.com/mlswg/mls-architecture/blob/main/draft-ietf-mls-architecture.md#compatibility-with-future-versions-of-mls ?
> 
> <img alt="image" width="838" src="https://user-images.githubusercontent.com/552961/210176367-d74f1861-2ac8-4fb7-beda-f8764ee24be6.png">

The screenshot from the mls-protocol spec basically talks about downgrade attacks, but does not address the two issues brought up:
- If a group is created with version x, can a client only supporting x-1 ever join the group. **A:** No, and that is a good thing.
- If a group is created with version x and all the members later support version x+1, how do clients "upgrade" the group. **A:** One of the members sends a ReInit prosposal which effectively moves the group to a new group with whatever version and group policies it wants that are supported by all the members.

**Comment by rohan-wire** [comment]
The WG discussed these issues at the 9-Feb-2023 interim and decided not to include these in the mls-architecture document.

1. We may write a standalone document describing more about migration scenarios, but all the necessary mechanisms exist in the mls-protocol. 
2. The choice of consistency model has a profound impact on client behavior and implementation. A specific profile of MLS is already a work item of the newly formed MIMI WG. We believe that discussion is a better place to elaborate on this topic.
3. Client removals are indeed annoying in MLS. A proposed extension is planned which will not change the cryptographic reality, but should prevent a leaving client from staying around for multiple Commits as an unwilling participant.

**Comment by beurdouche** [comment]
I have verified that we have now enough in the text with respect to the three point raised. Thank you !
