### ISSUE TITLE
Delivery Guarantees

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#197]
The Delivery Guarantees section requires quite a bit of familiarity with the details of MLS, specifically Add and Commit messages, but doesn't explain them. Do we really need to talk about these details here? If not, perhaps we could move some of this material to -protocol, where we wouldn't need this much explaining.

@bifurcation

**Comment by beurdouche** [comment]
We can still improve the text in Arch but protocol is out of auth-48 and ready to publish next week so that's not gonna happen.

**Comment by ekr** [comment]
There's no process obstacle to making that happen, it's merely a matter of whether it's worth doing.
