### ISSUE TITLE
Verify same client?

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#199]
The text reads:

> The Authentication Service (AS) has to provide three functionalities:
> ...
> 3. Enable a group member to verify that a credential represents the same client
>    as another credential

What is this referring to? @beurdouche @bifurcation

**Comment by ekr** [comment]
What is that way?

**Comment by Bren2010** [comment]
We don't specify the way, we just say the AS must provide one

**Comment by beurdouche** [comment]
@ekr Are you ok with closing this ?

**Comment by ekr** [comment]
Yeah, I can live with that.
