### ISSUE TITLE
Unconfirmed v. Confirmed Member

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-architecture#205]
When someone is added to a group we don't have confirmation from the user's consent until an update from that user which can be seen as a consent to join.

We need to discuss if we want to distinguish between unconfirmed/confirmed members or punt that to the application layer.

**Comment by ekr** [comment]
I think that one could get away without that concept as long as you made
the definition of "member" align to the one that dependent systems are
based on, which, it appears, means "unconfirmed member", whereas presently
the document defines "member" as "confirmed member".

**Comment by kkohbrok** [comment]
If you mean that we define member to generally mean "unconfirmed member" and then leave it up to the application layer to say what it means for a member to be considered "confirmed", I agree.

**Comment by ekr** [comment]
Yes, that's what I meant. This would require changing the text in the document, which has the opposite sense.

**Comment by ekr** [comment]
See proposed change in PR#208
