### ISSUE TITLE
More information about the DS computing the ratchet tree

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#212]
The text says:

>   - If assisted joining is desired (meaning that the ratchet tree is not
    provided in Welcome messages), there must be a method to download the
    ratchet tree corresponding to a group.
>  - If assisted joining is desired and the Delivery Service is not able to
    compute the ratchet tree itself (because some proposals or commits are sent
    encrypted), there must be a method for group members to publish the updated
    ratchet tree after each commit.

@bifurcation is there some way we can rewrite this in a way that doesn't require a lot of explanation about why the DS *would* be able to compute the ratchet tree.

**Comment by beurdouche** [comment]
Maybe something like:

"In cases where group operations are not encrypted, the DS has the ability to observe and maintain a copy of the public group state. In particular, this is useful for clients that do not have the ability to send the full public state in a Welcome message when inviting a user or for client that need to recover from a loss of their state."

**Comment by ekr** [comment]
LGTM

**Comment by beurdouche** [comment]
Ack. I'll make a PR

**Comment by beurdouche** [comment]
Fixed in https://github.com/mlswg/mls-architecture/commit/8a2977a02436f518d08e0b2c1ee2c3fd04a50b85
