### ISSUE TITLE
Many signature keys for one device

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#215]
> A policy for when two credentials represent the same client. Note that many
  credentials may be issued attesting to the same identity but for different
  signature keys, because each credential corresponds to a different device
  (client) owned by the same application user. However, one device may control
  many signature keys but should still only be considered a single client.

This last sentence probably needs some clarification. Do we have some motivating text for why this would happen? Different algorithms? Different time windows?

@bifurcation @beurdouche @kkohbrok

**Comment by Bren2010** [comment]
This would happen, for example, if a device rotates its signature key. The credential covering the old signature key may still be valid (expiration-wise) and included in groups. So group members need to be able to detect and prevent the same device from being added to a group twice by using different credentials.

**Comment by ekr** [comment]
Sure. Can you think of any common situation in which this would be "many" however? If not, I'll rewrite the text for clarity.

**Comment by Bren2010** [comment]
Perhaps in a case where credentials are issued with long lifetimes, but rotated frequently. Credentials may be issued as valid for a year, but rotated daily

**Comment by kkohbrok** [comment]
Rotating signature keys would also be my first thought. A client might rotate the signature key, update a few groups and then go offline before it has a chance to rotate the rest of the groups. When it comes online, it might rotate again and start with the same groups, etc. "Many" is probably not a common occurrence, but it's certainly a possibility.
