### ISSUE TITLE
Compartmentalized signing keys

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#220]
> > **RECOMMENDATION:** Signature private keys should be compartmentalized from
> other secrets and preferably protected by an HSM or dedicated hardware
> features to allow recovery of the authentication for future messages after a
> compromise.

This has a real RFC 6919 "MUST (BUT WE KNOW YOU WON'T)" flavor to it. Is there really WG consensus to recommend something which we don't really expect people to do?

**Comment by ekr** [comment]
This text seems even less realistic:

> > **RECOMMENDATION:** If messages are stored on the device, they should be
> protected using encryption at rest, and the keys used should be stored
> securely using dedicated mechanisms on the device.

The application itself needs to be able to decrypt these messages and users don't want to type in a password whenever the app starts, so the result is basically that this stuff has to be effectively in the clear.

**Comment by beurdouche** [comment]
About 1 -  It is true that most services won't but maybe your iPhone will store your signing keys in its secure enclave...
About 2 - This isn't suggesting hardware, but secure storage, which is often handled at the OS level.

Overall, I am encline to call this a wontfix... : )
