### ISSUE TITLE
Unidirectional transport

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#222]
> While it is difficult or impossible to prevent a network adversary from
suppressing payloads in transit, in certain infrastructures such as banks or
governments settings, unidirectional transports can be used and be enforced via
electronic or physical devices such as diodes. This can lead to payload
corruption which does not affect the security or privacy properties of the MLS
protocol but does affect the reliability of the service. In that case specific
measures can be taken to ensure the appropriate level of redundancy and quality
of service for MLS.

> RECOMMENDATION: If unidirectional transport is used for the secure
> transport channel, prefer using a transport protocol which provides Forward
> Error Correction.

This seems like a pretty niche use case. Given that we want MLS nodes to
routinely update keys, it's hard to see how a unidirectional transport is
going to work well. Moreover, none of our major transports provide FEC, so...

**Comment by beurdouche** [comment]
I agree this is niche but knowing of some of these use cases I think it is fine to keep this text and discard the recommendation. See https://github.com/mlswg/mls-architecture/pull/238
