### ISSUE TITLE
Mixnets?

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#223]
> > **RECOMMENDATION:** If real time notifications are not necessary, one can
> delay notifications randomly across recipient devices using a mixnet or other
> techniques.

This also seems fairly unrealistic.

**Comment by david415** [comment]
Are mixnets considered to be unrealistic? They do exist.

**Comment by rohan-wire** [comment]
We have received (paying) customer requests to do exactly this inside the Wire client. I think we should leave the recommendation.

**Comment by ekr** [comment]
OK. If it's something people are considering, then I agree we should keep it.
