### ISSUE TITLE
Strongest credential type

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#225]
> > **RECOMMENDATION:** Select the strongest MLS Credential type available among
> the target members of an MLS group.

What is this trying to say. Is it the strongest common type?

**Comment by ekr** [comment]
@bifurcation What do you think this is saying?

**Comment by Bren2010** [comment]
Don't use BasicCredential if everyone supports X509Credential. Don't use X509Credential if everyone supports _____ (fill in blank)

**Comment by rohan-wire** [comment]
> > > **RECOMMENDATION:** Select the strongest MLS Credential type available among
> > > the target members of an MLS group.
> 
> What is this trying to say. Is it the strongest common type?

The wording already in the recommendation seems like the clearest description of "strongest common type".

**Comment by ekr** [comment]
If I had found this clear, I wouldn't have needed to ask this question,

**Comment by beurdouche** [comment]
"strongest" what is the question... I'll clarify...

**Comment by ekr** [comment]
My concern wasn't strongest but "available"

**Comment by ekr** [comment]
See: https://github.com/mlswg/mls-architecture/pull/235
