### ISSUE TITLE
Service binding separation

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#228]
> **RECOMMENDATION:** Separate the service binding the identities and the public
> keys from the service which generates or validates the credentials or
> cryptographic material of the Clients.

What is this trying to say?

**Comment by ekr** [comment]
@bifurcation?

**Comment by beurdouche** [comment]
I rephrased in https://github.com/mlswg/mls-architecture/commit/7dada751e2388a776c4ff8da0884dc845458ced6
