### ISSUE TITLE
Recommendation about Lifetimes and LeafNodes and KeyPackages

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-architecture#233]

**Comment by ekr** [comment]
@beurdouche do you know what you want to do here? It's not clear to me from the title what the issue is

**Comment by beurdouche** [comment]
There is currently no recommendation on lifetimes of keys: should key expire after days, weeks, months, years ?
At this point I am leaning toward not offering any specific recommendation and keep the current language: "should be updated on a regular basis" but I am looking for other opinions...

**Comment by ekr** [comment]
I think that's fine.

**Comment by beurdouche** [comment]
Discussed above with Ekr. Wontfix.
