### ISSUE TITLE
ReInit on network partition

### ISSUE THREAD

**Issue by vwesselkamp** [mlswg/mls-architecture#234]
> In the event of a network partition, a subset of members may be isolated from the rest of the group long enough that the mechanisms above no longer work. This can only be solved by sending a ReInit proposal to both groups, possibly with an external sender type, and recreating the group to contain all members again.

From the paragraph, I don’t fully understand the case where this mechanism could be applied: 

To process a ReInit, a member needs the resumption PSK of the epoch after the ReInit was committed and hence only members who can properly process the newest commit of the group can perform the ReInit. Then doesn't that require that the isolated subset has caught up with the rest of the group anyway? So why even reinitialize? 
Or, put the other way around, it seems the network partition describes the case where a subset of the group cannot transition epoch with the rest of the group (e.g. because they accepted a different commit and haven’t kept the old state), but in that case, how can they get access to the PSK required for the ReInit? 

It would be great to clarify this.

**Comment by ekr** [comment]
@bifurcation ?

**Comment by beurdouche** [comment]
Fixed in #240
