### ISSUE TITLE
Confusing wording about key material sharing

### ISSUE THREAD

**Issue by istankovic** [mlswg/mls-architecture#254]
[Here](https://github.com/mlswg/mls-architecture/blob/d5f7bb8a0cfa00fb1e815aa12629d848652c18b9/draft-ietf-mls-architecture.md?plain=1#L596-L599) we have:
```
The association between members' identities and signature keys is fairly
flexible in MLS.  As noted above, there is no requirement that all clients
belonging to a given user use the same key pair (in fact, such key reuse is
forbidden to ensure clients have independent cryptographic state).  A member can
```

However, in section 6.1, [we have](https://github.com/mlswg/mls-architecture/blob/d5f7bb8a0cfa00fb1e815aa12629d848652c18b9/draft-ietf-mls-architecture.md?plain=1#L819-L822):
```
most cases, a client corresponds to a specific device used by a user. If a user
has multiple devices, the user will generally be represented in a group by
multiple clients (although applications could choose to have devices share
keying material).  If an application wishes to implement operations at the level
```

It appears that the two paragraphs are conflicting each other (forbidden key reuse vs. sharing key material).
It would be good to clarify precisely which key material/keys are being referred to in both places to avoid confusion,
especially since there are recommendations further in the document to avoid key sharing.

**Comment by seanturner** [comment]
Can I get a volunteer to draft up a PR? See [email](https://mailarchive.ietf.org/arch/msg/mls/UgfHJZKdvGAG6ETQWwfamQ254kM/).
