### ISSUE TITLE
de-2119 the draft

### ISSUE THREAD

**Issue by seanturner** [mlswg/mls-architecture#35]
In some sense there's a bit of style to this, but we do not necessary need to use 2119-language in this document.  As discussed at the [27-28 September 2019 Interim meeting](https://github.com/mlswg/wg-materials/blob/master/interim-2018-09/agenda.md) during our ways of working section, we decided that we did not need to use 2119 language.  In fact there was only one instance and it could be removed.

**Comment by beurdouche** [comment]
This seems done, should we close ?
