### ISSUE TITLE
Ghost Users / Authn Security Considerations

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#44]
In some authentication regimes, it is possible for the authentication service to attest that a public key is bound to an identity, when in reality the holder of the identity does not hold the corresponding private key.  This problem is related to the question of how the problem of re-instantiating users after device loss/failure.   We should discuss what should go in the document around these problems.

**Comment by katrielalex** [comment]
We discussed this at the interim; cc @joncallas and @ekr to write a paragraph in the architecture document. While we have a single authentication service, we don't want to rule out having other ways to verify its actions (e.g., fingerprint QR scans, or key transparency logs).

**Comment by beurdouche** [comment]
Fixed by ca3ccb293856fb6c786bd4acde759a03bcdabc54
