### ISSUE TITLE
Access control policy

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#45]
The architecture document should discuss the application of policies that control which users can take which group actions (e.g., Add, Remove), and how such policies can be implemented in a given protocol deployment.  It seems like there are broadly two cases:

* If handshake messages are unencrypted, then the server can enforce policy at the stage when it does handshake message sequencing and fanout

* If handshake messages are encrypted, then policy needs to be enforced by clients

In either case, the policy needs to be consistent -- all clients need to make the same decision as to whether to apply a change or not.

**Comment by beurdouche** [comment]
279fda82c2046b1ff10deeea0d8eb728937c7ae6
