### ISSUE TITLE
Improve description of out-of-bound authentication for the AS

### ISSUE THREAD

**Issue by burdges** [mlswg/mls-architecture#51]
Authentication services actually required?  Or would TOFU be as secure as it usually is? 

At least one distributed group messenger (Riot/Matrix) has the *extremely* insecure practice of prompting users to verify keys with a pop-up.  Is there perhaps some problem with TOFU in the group messaging setting?

It's probably good to address TOFU regardless, even if only saying that you do not know if it's security properties change.

**Comment by kdenhartog** [comment]
It talks about this a bit (implicitly describing solutions) in the last paragraph of the [authentication service section](https://github.com/mlswg/mls-architecture/blob/master/draft-ietf-mls-architecture.md#authentication-service). Would you think it would be useful to add additional details about handling TOFU? 

The only additional thing I can think that could be done do to add additional trust is to use randomart images for users to verify and image in an out-of-band channel. This is a slightly better UX than what's in most e2e apps today, but doesn't change the security properties in any way so I would consider it out of scope for this spec.

**Comment by ntninja** [comment]
After reading the architectural draft today (me: random crypto-interested developer), I was surprised that there was no mention of out-of-band authentication to protect against malicious/compromised Authentication Services at all. Specifying the UX in *how* that happens (QR codes, emojis, identicons, what-have-you) is understandably out-of-scope, but the idea of giving users the ability of verifying each other's crystallographic identifiers in-person, seems like a very strong mitigating of this risk – even if not practical in every scenario.

**Comment by beurdouche** [comment]
Noted, thanks ! : )

**Comment by beurdouche** [comment]
Serveral changes and improvement have been made to the document, please open a PR if the document is not complete enough.
