### ISSUE TITLE
Delivery assumption

### ISSUE THREAD

**Issue by burdges** [mlswg/mls-architecture#52]
I'm curious about the delivery assumption on the Delivery Service in 2.3.3.  There are sensible transports that violate all of reliable delivery, in-order delivery, and consistent ordering.   Anyone commented about the failure modes when violating these assumptions? 

At least in-order delivery requirement appears quite soft, except the metadata gets leaked if not protected by MLS.  If so, applications should modify MLS by adding header encryption, like in good Axolotl ratchet implementations.

There is already a hash iteration ratchet which I suppose helps address these problems.

**Comment by beurdouche** [comment]
This section has been rewritten and should be better now...
