### ISSUE TITLE
Clarification wanted: Messaging Service

### ISSUE THREAD

**Issue by GaPhil** [mlswg/mls-architecture#62]
In the context of this document, the meaning of the term _Messaging Service (MS)_ seems a little unclear to me. The document states that the protocol is _intended to be embedded in a concrete protocol such as XMPP_. However, is a MS meant to be a messaging service such as SMS or MMS? Or a service on the application layer, such as FB or WhatsApp? Essentially who provides / controls the AS and DS? I would be grateful for some clarification on this. Thanks.

**Comment by beurdouche** [comment]
It is meant to mean application layer, would changing that to "service provider" work better for you?

**Comment by GaPhil** [comment]
Thank you. I do think that the term _service provider_ is less ambiguous.

**Comment by beurdouche** [comment]
Ack, will fix soon.

**Comment by GaPhil** [comment]
I can make a PR, if you want?

**Comment by beurdouche** [comment]
> I can make a PR, if you want?

Sure, please go for it.

**Comment by beurdouche** [comment]
Fixed by #63
