### ISSUE TITLE
Handling user permissions in MLS versus implementations

### ISSUE THREAD

**Issue by chelseakomlo** [mlswg/mls-architecture#68]
The last paragraph of the "General Settings" section states: 

> At the cryptographic level, clients (and by extension members in groups) have equal permissions. For instance, any member can add or remove another client in a group. This is in contrast to some designs in which there is a single group controller who can modify the group. MLS is compatible with having group administration restricted to certain users, but we assume that those restrictions are enforced by authentication and access control at the application layer. Thus, for instance, while it might be cryptographically possible for any member to send a message adding a new client to a group, the group might have the policy that only certain members are allowed to make changes and thus other members can ignore or reject such a message from an unauthorized user.

Isn't the last sentence overly prescriptive of how group messaging applications that implement MLS might handle unauthorized user actions? The current wording makes it sound like members (i.e, users) themselves are responsible for ignoring/rejecting unauthorized user messages, which seems not quite right. 

If applications will actually handle enforcing these policies as part of their UX, I recommend changing the last sentence to something like "Thus, for instance, while the MLS protocol allows for any existing member of a group to add a new client, the group messaging application which implements MLS might allow for group administration policies for which only a subset of members can qualify, and thus will handle enforcing group policies (such as determining if a user is allowed to add new users to the group) at the application level."

**Comment by beurdouche** [comment]
Thanks for the comment! : ) 
I tried to clarify that paragraph in https://github.com/mlswg/mls-architecture/commit/a2200df1e0007a56aeb2c6ea9a7da5df7e47b6bb
