### ISSUE TITLE
Editor's copy points to a 404.

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-architecture#70]
The build and GH actions script seem to work now, thanks @Bren2010 .

The README points to an Editor's copy which is 404.
https://mlswg.github.io/mls-architecture/#go.draft-ietf-mls-architecture.html

The artifact seem to build properly though:
https://github.com/mlswg/mls-architecture/actions/runs/176901329

@katrielalex @Bren2010 Are we missing a redirect or something?

**Comment by Bren2010** [comment]
- It doesn't look like Pages it on. You can try turning it on and off in the Settings tab and that will trigger a new deploy.
- Leave the domain for Pages as the default, not "architecture.messaginglayersecurity.rocks" or something similar

**Comment by beurdouche** [comment]
@katrielalex I think, only you can do that, I only have write access, so I don't have the "Settings" tab... :/

**Comment by katrielalex** [comment]
Hm strange: 
![image](https://user-images.githubusercontent.com/315959/88268657-b5932180-ccca-11ea-92fa-f77069f7784c.png)

**Comment by katrielalex** [comment]
Turned it off and on again and now I see

![image](https://user-images.githubusercontent.com/315959/88269008-33efc380-cccb-11ea-9de9-b7367e31baf6.png)

**Comment by katrielalex** [comment]
mls-protocol shows

![image](https://user-images.githubusercontent.com/315959/88269046-4538d000-cccb-11ea-8dc5-0569cf9b6820.png)

so I think this might just need another commit to trigger the build

**Comment by beurdouche** [comment]
Yay, it seems to work now !! 👍 Thanks a lot Katriel and Brendan !!
