### ISSUE TITLE
Client-side fanout

### ISSUE THREAD

**Issue by ShivanKaul** [mlswg/mls-architecture#76]
There is some text in a couple of places in the architecture draft that mentions client-side vs server-side fanout. The main tradeoff seems to be performance vs the DS learning metadata. Would some implementations might want to err more on the side of the server learning less - would this be useful guidance to have in the arch draft? Separate draft? Else, if the thought is that this is totally out-of-scope, it would be worthwhile calling it out explicitly.

**Comment by beurdouche** [comment]
Thanks for the question : )
This is an interesting discussion to have, even though we can't really be exhaustive in the descriptions, I think we can make some space to describe the tradeoffs as part as https://github.com/mlswg/mls-architecture/issues/75
So I'll close this issue and reference it there.
